### ISSUE TITLE
Speicherung der vorherigen Werte

### ISSUE THREAD

**Issue by HansPeterMeier** [hdering/homematic_stromverbrauch_protokollieren#1]
Erst mal vielen Dank für dein Script.
ich bin im Moment auf der Suche nach einem ausfallsicheren Script, da das jetzige leider nach einen Neustart die Werte verliert.
Das ist ungünstig.

Was ich mir wünschen würde.
Speicherung des vorherigen Tages, Woche, Monat und Jahr.
Also den Wert kurz vor Mitternacht eben rüberschicken auf vorheriger Tag usw.
Das kann man dann schön mit History loggen.
Mal schauen ob ich meine WMBus Wärmemengenzähler auch integrieren kann.

Gruß

**Comment by hdering** [comment]
Hi HansPeterMeier,

was meinst du mit "nach einem Neustart"? Wenn das Skript neugestartet wird, verliert es die Werte?

> Speicherung des vorherigen Tages, Woche, Monat und Jahr.
> Also den Wert kurz vor Mitternacht eben rüberschicken auf vorheriger Tag usw.
> Das kann man dann schön mit History loggen.

Bitte erläutere das genauer z.B. an einem Beispiel.

Willst du praktisch dass, wenn ein neuer Tag beginnt, der alte Wert in einer zusätzlichen Variable steht?

**Comment by HansPeterMeier** [comment]
Das mit dem verlieren der Werte nach einem Stromausfall ist bei einem anderen Script aus dem Forum. Dass schöne an den anderen Script ist, das der alte Wert für Tag, Woche usw. in einem zusätzlichen Datenbank geschrieben wird. Somit lasse ich mir die Werte aktuellen Verbrauch heute und den tagesverbrauch Gestern anzeigen.
Ich hoffe das ich heute Abend dein Script mal ans laufen bekomme, vielleicht hättest du noch Lust weitere Features aufzunehmen.

Gruß und danke

**Comment by hdering** [comment]
Hallo HansPeterMeier,

dieses Skript fängt einen Neustart des Gerätes bzw. der CCU ab. Der Wert wächst einfach immer weiter.

Ich werde etwas einbauen, damit man sich beliebig viele Werte in der Vergangenheit speichern kann.

Wenn du Features hast, erstelle einfach ein Issue.

**Comment by hdering** [comment]
Mit Version 1.0.7 werden am Ende des Tages die Werte in eine andere Variable geschrieben.
