### ISSUE TITLE
AVM DECT- und Powerline-Steckdosen

### ISSUE THREAD

**Issue by Kampfratte** [hdering/homematic_stromverbrauch_protokollieren#2]
Hallo

Super Script. Vielen dank dafür.

wollte nur mitteilen, dass das Script auch mit AVM-Steckdosen, die im ioBroker mit eingebunden sind, funktionieren, wenn diese über "eigene Datenpunkte" hinzu gefügt wurden. Ich hab 2 DECT- und zwei Powerlinesteckdosen mit drin. Selbst diese vier werden mit geloggt.

Einziger Nachteil, den ich gefunden habe. Bei einem neuen Tag werden die Daten des aktuellen Tages erst in Tag 1 (gestern) geschrieben, wenn der Verbraucher ein war und wieder neu Leistung gemessen wurde. Könnte man das nicht so bauen, dass die Daten nachts automatisch rüber geschrieben werden und der aktuelle Tag automatisch wieder auf 0 ist und nicht erst, wenn der Verbraucher das erste mal eingeschalten wird. Habe ja ein paar Steckdosen mit Verbrauchern, die nicht jeden Tag laufen.
Denke mal, dass dies bei Wochen, Quartalen, Monaten und Jahren genau so ist.

**Comment by hdering** [comment]
Vielen Dank für dein Feedback.

Mit Version 1.2.0 werden die Werte direkt um 0 Uhr zurückgesetzt.
