### ISSUE TITLE
Wunsch: 2-Tarif-Zähler

### ISSUE THREAD

**Issue by mcmuller** [hdering/homematic_stromverbrauch_protokollieren#4]
Danke für das nette Skript! Falls Du das weiterentwickeln willst (ich kann das leider nicht...), würde ich mir einen 2-Tarifzähler wünschen. Ich habe hier von 22:00h bis 07:59h einen anderen Tarif als von 08:00h bis 21:59h. Ach ja, und Grundpreis ist hier täglich, also Tage/Monat abhängig.
Nochmal: Dankeschön, so wie es ist, der Rest ist purer Traum :-)

**Comment by hdering** [comment]
Programmtechnisch umzusetzen, ist, glaube ich, ganz schön aufwendig...

**Comment by hdering** [comment]
Wir haben es schon soweit, das jedes Gerät seinen eigenen Strompreis haben kann.
